### ISSUE TITLE
Depend on PSR-18

### ISSUE THREAD

**Issue by ricardofiorani** [ricardofiorani/php-cloudflare-amp-validator#10]
https://github.com/php-fig/fig-standards/tree/master/proposed/http-client/

Nullifies #6

**Comment by nawarian** [comment]
From what I've understood PSR-18 won't support async calls. This might no be wanted for this project.

The Client Interface defines the `sendRequest()` method as returning a `ResponseInterface` instead of a Promise, therefore you must always execute synchronous calls.

**Comment by ricardofiorani** [comment]
@nawarian we don't gonna need async for now due to the way this package was designed. But this is a feature that I will keep in mind for future versions (once there is a PSR specifying on how async calls should work)
