### ISSUE TITLE
Add PSR-17 support

### ISSUE THREAD

**Issue by ricardofiorani** [ricardofiorani/php-cloudflare-amp-validator#12]
# Status quo
Today our constructor method receives only an PSR-18 HTTP Client, however, we instantiate manually the request. (As can be seem in https://github.com/ricardofiorani/php-cloudflare-amp-validator/blob/master/src/Validator/Validator.php#L41)

# Todo
Make it possible to send an PSR-17 RequestFactory optional argument on the constructor, which will be used to create the request. If none is passed, we instantiate a new RequestFactory of our choice.

**Comment by lex111** [comment]
Can I have more details to implement this?

**Comment by mkingbe** [comment]
WIP
